### ISSUE TITLE
Determine Which Official Logos to use for CMS Distros

### ISSUE THREAD

**Issue by andrew-c-tran** [drud/style.drud.com#1]
## Research Request
In many part of our UI, we use CMS logos as an identifier for the CMS and version that we are referring to. We need to determine a standard set of icons for each to ensure consistency across the UI.

Square (similar x/y dimensions, not necessarily square logos) format logos are preferred as the shape of the UI cards are square. 

Drupal 8 has a standard iconography document/media kit with GPL'd assets, and can be found:
https://www.drupal.org/about/media-kit/logos

Drupal 7, however, doesn't seem to have a media kit, nor from what i've found is there an "official" drupal 7 logo.

Wordpress has a logo and color branding guide here:
https://wordpress.org/about/logos/

## Acceptance Criteria:

- [x] Drupal 7 logo
- [x] Drupal 8 logo
- [x] Wordpress logo

**Comment by cyberswat** [comment]
It seems reasonable that we should include [Typo3](https://typo3.org/about/the-brand/style-guide/the-typo3-logo/).

**Comment by cyberswat** [comment]
@andrew-c-tran I took an initial pass at adding standard logos to use with wordpress, drupal 7, drupal 8, typo3 and ddev.  Let me know if that works for this issue.

**Comment by andrew-c-tran** [comment]
Looks good, the dimensions and size are perfect. Is the drop with the face a widely known "7" icon in drupalland?
